#!/bin/sh
echo "[rcS] starting system initialization"

[ -d /dev ] || mkdir -p /dev

[ -c /dev/console ] || mknod /dev/console c 5 1
[ -c /dev/null ]    || mknod /dev/null c 1 3


chmod 600 /dev/console
chmod 666 /dev/null

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "[rcS] initialization complete"
